{
 "title": "Monitoramento de Votos",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Infra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_usage_bytes", "legendFormat": "Memory" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "targets": [
    { "expr": "memory_usage_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 9 },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Active Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "active_requests{job=\"voting-app\"}",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "active_requests{job=\"voting-app\"}",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(response_time_seconds_sum[1m])) by (route, method)/avg(rate(response_time_seconds_count[1m])) by (route, method)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Taxa de Requisições Por Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(response_time_seconds_count[1m])) by (route, method)",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(query_duration_seconds_sum[1m])) by (query_type) / avg(rate(query_duration_seconds_count[1m])) by (query_type)",
     "legendFormat": "{{query_type}}"
    }
   ]
  }
 ]
}